# Generated by Django 5.1.1 on 2024-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='fruits',
            name='clas',
            field=models.CharField(choices=[('Extra', 'extra'), ('Primeira', 'primeira'), ('Segunda', 'segunda'), ('Terceira', 'terceira')], max_length=10),
        ),
    ]
