# Generated by Django 5.1.1 on 2024-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_delete_user_alter_fruits_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=10)),
                ('hour', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
