# Generated by Django 5.1.1 on 2024-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='hour',
            field=models.CharField(max_length=15),
        ),
    ]
