# Generated by Django 5.1.1 on 2024-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_sell_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='salesman',
            field=models.CharField(default='nome', max_length=20),
        ),
    ]
